(()=>{"use strict";
const URL="https://ccdllfswfhtgcolkugbz.supabase.co",KEY="sb_publishable_LPd-zxWUKM8c1p2P9sbbuA_EmhtqQr5";
if(!window.supabase){document.getElementById("menu-info").textContent="Supabase failed to load. Open this page through Live Server (http://), not file://.";return}
const sb=window.supabase.createClient(URL,KEY),$=id=>document.getElementById(id),canvas=$("game-canvas"),ctx=canvas.getContext("2d",{alpha:false});
let W=0,H=0,state="START",last=0,user,profile,crix=10,score=0,xp=0,level=1,lives=3,player,bullets=[],enemies=[],stars=[],sparks=[],spawn=0,fireClock=0,abilityClock=0,invuln=0,left=false,right=false,fire=false,weapon={damage:25,delay:.22,dual:false,color:"#76ff03"};
const music=new Audio("sounds/gameplay_music.flac");music.loop=true;music.volume=.28;
function musicOn(){music.play().catch(()=>{})}function sound(id){const a=$(id);if(!a)return;try{a.currentTime=0;a.play().catch(()=>{})}catch(e){}}
document.addEventListener("mouseover",e=>{if(e.target.closest("button"))sound("uiHover")});document.addEventListener("click",e=>{if(e.target.closest("button")){sound("uiClick");musicOn()}});
function resize(){W=canvas.clientWidth;H=canvas.clientHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(W*d);canvas.height=Math.floor(H*d);ctx.setTransform(d,0,0,d,0,0);if(player){player.y=H-105;player.x=Math.max(24,Math.min(W-24,player.x))}}
addEventListener("resize",resize);
const SHIPS=[{hp:55,r:13,s:75,score:12,c:"#32e6ff"},{hp:95,r:15,s:92,score:20,c:"#76ff03"},{hp:150,r:17,s:70,score:32,c:"#a55eea"},{hp:240,r:20,s:58,score:55,c:"#ff9d35"},{hp:390,r:23,s:45,score:90,c:"#ff3f67"}];
function xpNeed(l){return Math.floor(100*Math.pow(1.8,l-1))}function levelFor(x){let l=1,total=0;while(l<50){total+=xpNeed(l);if(x<total)return l;l++}return l}
async function boot(){try{const {data:{session}}=await sb.auth.getSession();if(!session){location.replace("login.html");return}user=session.user;let p=await sb.from("player_profiles").select("*").eq("id",user.id).maybeSingle();if(p.error)throw p.error;if(!p.data){p=await sb.from("player_profiles").insert({id:user.id,username:user.email?.split("@")[0]||"PILOT",crix:10,m_tokens:0}).select().single();if(p.error)throw p.error}profile=p.data;crix=Number(profile.crix||0);const l=await sb.from("player_loadouts").select("*").eq("player_id",user.id).maybeSingle();const items=await sb.from("game_items").select("*").eq("is_shop_visible",true);const w=(items.data||[]).find(x=>x.id===l.data?.weapon_id);if(w?.stats)weapon={damage:Number(w.stats.damage||25),delay:Number(w.stats.fireDelay||.22),dual:Boolean(w.stats.dual),color:"#76ff03"};resize();menu();draw()}catch(e){console.error(e);$("menu-info").textContent="Could not load mission data. Serve the game with Live Server and sign in again."}}
function menu(){ $("menu-title").textContent="MISSION READY";$("menu-info").innerHTML="V2 COMBAT SYSTEMS ONLINE<br><br><b>WASD / ARROWS</b> move · <b>SPACE</b> fire · <b>E</b> ability<br>Enemies become faster and tougher as your level rises.<br><br>Weapon damage: <b>"+weapon.damage+"</b> · Fire rate: <b>"+(1/weapon.delay).toFixed(1)+"/s</b>"}
function reset(){score=0;xp=0;level=1;lives=3;spawn=.4;fireClock=0;abilityClock=0;invuln=0;bullets=[];enemies=[];sparks=[];player={x:W/2,y:H-105,r:11,max:100,hp:100};stars=Array.from({length:150},()=>({x:Math.random()*W,y:Math.random()*H,s:.4+Math.random()*1.5,v:15+Math.random()*45}));hud()}
function hud(){$("score-display").textContent=score;$("level-display").textContent=level;$("lives-display").textContent=lives;$("cret-display").textContent=Math.floor(crix);$("xp-display").textContent=xp;$("next-xp-display").textContent=xpNeed(level);$("player-hp-fill").style.width=Math.max(0,player?player.hp/player.max*100:100)+"%";$("ability-bar-fill").style.width=Math.max(0,(1-abilityClock/8)*100)+"%"}
function toast(t){$("temp-message-container").textContent=t;clearTimeout(toast.t);toast.t=setTimeout(()=>$("temp-message-container").textContent="",850)}
function launch(){reset();state="RUNNING";$("message-box").style.display="none";musicOn();last=performance.now();requestAnimationFrame(loop)}
function finish(){state="OVER";$("message-box").style.display="grid";$("menu-title").textContent=lives?"MISSION ENDED":"SHIP DESTROYED";$("menu-info").innerHTML="SCORE <b>"+score+"</b> · XP <b>"+xp+"</b> · LEVEL <b>"+level+"</b><br><br>Ready for another sortie?";$("start-button").textContent="LAUNCH AGAIN"}
function hit(a,b){const dx=a.x-b.x,dy=a.y-b.y;return dx*dx+dy*dy<(a.r+b.r)**2}
function spawnEnemy(){const s=SHIPS[Math.floor(Math.random()*SHIPS.length)],d=1+(level-1)*.13;enemies.push({x:20+Math.random()*(W-40),y:-30,r:s.r,hp:s.hp*d,max:s.hp*d,s:s.s*(1+level*.012),score:s.score,c:s.c,damage:s.r*2*d})}
function shoot(){if(state!=="RUNNING"||fireClock>0)return;fireClock=weapon.delay;bullets.push({x:player.x,y:player.y-18,v:680,r:3,d:weapon.damage});if(weapon.dual){bullets.push({x:player.x-9,y:player.y-13,v:680,r:3,d:weapon.damage*.7},{x:player.x+9,y:player.y-13,v:680,r:3,d:weapon.damage*.7})}}
function ability(){if(state!=="RUNNING"||abilityClock>0)return;abilityClock=8;for(const e of enemies)e.hp-=weapon.damage*3;toast("PULSE // IMPACT")}
function damage(n){if(invuln>0)return;invuln=.6;player.hp-=n;if(player.hp<=0){lives--;if(lives<=0){hud();finish();return}player.hp=player.max;toast("HULL BREACH // LIFE LOST")}hud()}
function update(dt){if(left)player.x-=250*dt;if(right)player.x+=250*dt;player.x=Math.max(22,Math.min(W-22,player.x));if(fire)shoot();fireClock=Math.max(0,fireClock-dt);abilityClock=Math.max(0,abilityClock-dt);invuln=Math.max(0,invuln-dt);spawn-=dt;if(spawn<=0){spawnEnemy();spawn=Math.max(.22,1.05/(1+level*.05))}for(const b of bullets)b.y-=b.v*dt;bullets=bullets.filter(b=>b.y>-30);for(const e of enemies){e.y+=e.s*dt;if(hit(e,player)){damage(e.damage);e.hp=0}}for(const b of bullets)for(const e of enemies)if(e.hp>0&&hit(b,e)){e.hp-=b.d;b.y=-100;if(e.hp<=0){score+=e.score;burst(e.x,e.y,e.c);toast("+"+e.score+" SCORE")}break}enemies=enemies.filter(e=>e.hp>0&&e.y<H+50);xp=Math.floor(score/10);const nl=levelFor(xp);if(nl>level){level=nl;toast("LEVEL UP // "+level)}hud()}
function burst(x,y,c){for(let i=0;i<12;i++)sparks.push({x,y,vx:(Math.random()-.5)*150,vy:(Math.random()-.5)*150,t:.35,c})}
function ship(x,y){ctx.save();ctx.translate(x,y);ctx.globalAlpha=invuln>0&&Math.floor(invuln*15)%2===0?.3:1;ctx.shadowBlur=18;ctx.shadowColor="#00eaff";ctx.fillStyle="#00eaff";ctx.beginPath();ctx.moveTo(0,-18);ctx.lineTo(12,13);ctx.lineTo(4,9);ctx.lineTo(0,17);ctx.lineTo(-4,9);ctx.lineTo(-12,13);ctx.closePath();ctx.fill();ctx.fillStyle="#dffcff";ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(4,6);ctx.lineTo(-4,6);ctx.closePath();ctx.fill();ctx.fillStyle="#39ddff";ctx.fillRect(-2,12,4,12);ctx.restore();ctx.globalAlpha=1;ctx.shadowBlur=0}
function enemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(Math.PI);ctx.shadowBlur=14;ctx.shadowColor=e.c;ctx.fillStyle=e.c;ctx.beginPath();ctx.moveTo(0,-e.r*1.2);ctx.lineTo(e.r,e.r*.7);ctx.lineTo(0,e.r*.35);ctx.lineTo(-e.r,e.r*.7);ctx.closePath();ctx.fill();ctx.restore();ctx.shadowBlur=0;const w=e.r*2.5;ctx.fillStyle="#19070b";ctx.fillRect(e.x-w/2,e.y-e.r-8,w,3);ctx.fillStyle="#ff405d";ctx.fillRect(e.x-w/2,e.y-e.r-8,w*Math.max(0,e.hp/e.max),3)}
function draw(){ctx.fillStyle="#02040a";ctx.fillRect(0,0,W,H);for(const s of stars){s.y+=s.v/60;if(s.y>H)s.y=0;ctx.fillStyle="rgba(255,255,255,.65)";ctx.fillRect(s.x,s.y,s.s,s.s)}for(const p of sparks){p.x+=p.vx/60;p.y+=p.vy/60;p.t-=.018;ctx.globalAlpha=Math.max(0,p.t/.35);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,3,3)}ctx.globalAlpha=1;sparks=sparks.filter(p=>p.t>0);for(const b of bullets){ctx.fillStyle=weapon.color;ctx.shadowBlur=9;ctx.shadowColor=weapon.color;ctx.fillRect(b.x-2,b.y-8,4,13)}ctx.shadowBlur=0;for(const e of enemies)enemy(e);if(player)ship(player.x,player.y)}
function loop(t){if(state!=="RUNNING")return;const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}
function hold(id,set){const b=$(id),on=e=>{e.preventDefault();set(true);musicOn()},off=e=>{e.preventDefault();set(false)};b.addEventListener("pointerdown",on);b.addEventListener("pointerup",off);b.addEventListener("pointercancel",off);b.addEventListener("pointerleave",off)}
hold("move-left-btn",v=>left=v);hold("move-right-btn",v=>right=v);hold("fire-btn",v=>fire=v);$("ability-btn").addEventListener("pointerdown",e=>{e.preventDefault();ability()});$("start-button").addEventListener("click",launch);
addEventListener("keydown",e=>{if(e.code==="ArrowLeft"||e.code==="KeyA")left=true;if(e.code==="ArrowRight"||e.code==="KeyD")right=true;if(e.code==="Space")fire=true;if(e.code==="KeyE")ability();if(e.code==="Enter"&&state!=="RUNNING")launch();if(["ArrowLeft","ArrowRight","Space"].includes(e.code))e.preventDefault()});addEventListener("keyup",e=>{if(e.code==="ArrowLeft"||e.code==="KeyA")left=false;if(e.code==="ArrowRight"||e.code==="KeyD")right=false;if(e.code==="Space")fire=false});
boot();
})();